/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ttaiit.blogspot.com;

import javax.swing.ImageIcon;

/**
 *
 * @author Administrator
 */
public class NavigateImages2 extends javax.swing.JFrame {

    /**
     * Creates new form NavigateImages2
     */
    public NavigateImages2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Image1 = new javax.swing.JLabel();
        bNext = new javax.swing.JButton();
        Image2 = new javax.swing.JLabel();
        bNext2 = new javax.swing.JButton();
        bNext3 = new javax.swing.JButton();
        Image3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(0, 0));

        Image1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ttaiit/blogspot/com/images/1a.jpg"))); // NOI18N
        Image1.setText("jLabel1");
        Image1.setAlignmentY(0.0F);
        Image1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        Image1.setIconTextGap(0);

        bNext.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        bNext.setText("Next");
        bNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNextActionPerformed(evt);
            }
        });

        Image2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ttaiit/blogspot/com/images/2a.jpg"))); // NOI18N
        Image2.setText("jLabel1");
        Image2.setAlignmentY(0.0F);
        Image2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        Image2.setIconTextGap(0);

        bNext2.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        bNext2.setText("Next");
        bNext2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNext2ActionPerformed(evt);
            }
        });

        bNext3.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        bNext3.setText("Next");
        bNext3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNext3ActionPerformed(evt);
            }
        });

        Image3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ttaiit/blogspot/com/images/3a.jpg"))); // NOI18N
        Image3.setText("jLabel1");
        Image3.setAlignmentY(0.0F);
        Image3.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        Image3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Image3.setIconTextGap(0);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Image1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Image2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Image3, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bNext)
                    .addComponent(bNext3)
                    .addComponent(bNext2))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Image1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bNext))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Image2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bNext2))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Image3, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bNext3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int count = 0;
    String[] imagenames = {"1a.jpg","1b.jpg","1c.jpg","1d.jpg","1e.jpg","1f.jpg","1g.jpg","1h.jpg"};
    private void bNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNextActionPerformed
        ImageIcon[] imagelist = new ImageIcon[8];
        for(int i = 0; i < imagelist.length; i++){
            imagelist[i] = new ImageIcon(getClass().getResource("/ttaiit/blogspot/com/images/" + imagenames[i]));
        }
        if(count < imagenames.length - 1){
            count ++;
            Image1.setIcon(imagelist[count]);
        }
        else if(count == imagenames.length - 1){
            count = 0;
            Image1.setIcon(imagelist[count]);
        }
    }//GEN-LAST:event_bNextActionPerformed

    int count2 = 0;
    String[] imagenames2 = {"2a.jpg","2b.jpg","2c.jpg","2d.jpg","2e.jpg","2f.jpg","2g.jpg","2h.jpg"};
    private void bNext2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNext2ActionPerformed
        ImageIcon[] imagelist2 = new ImageIcon[8];
        for(int i = 0; i < imagelist2.length; i++){
            imagelist2[i] = new ImageIcon(getClass().getResource("/ttaiit/blogspot/com/images/" + imagenames2[i]));
        }
        if(count2 < imagenames2.length - 1){
            count2 ++;
            Image2.setIcon(imagelist2[count2]);
        }
        else if(count2 == imagenames2.length - 1){
            count2 = 0;
            Image2.setIcon(imagelist2[count2]);
        }
    }//GEN-LAST:event_bNext2ActionPerformed
    
    int count3 = 0;
    String[] imagenames3 = {"3a.jpg","3b.jpg","3c.jpg","3d.jpg","3e.jpg","3f.jpg","3g.jpg","3h.jpg"};
    private void bNext3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNext3ActionPerformed
        ImageIcon[] imagelist3 = new ImageIcon[8];
        for(int i = 0; i < imagelist3.length; i++){
            imagelist3[i] = new ImageIcon(getClass().getResource("/ttaiit/blogspot/com/images/" + imagenames3[i]));
        }
        if(count3 < imagenames3.length - 1){
            count3 ++;
            Image3.setIcon(imagelist3[count3]);
        }
        else if(count3 == imagenames3.length - 1){
            count3 = 0;
            Image3.setIcon(imagelist3[count3]);
        }
    }//GEN-LAST:event_bNext3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NavigateImages2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NavigateImages2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NavigateImages2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NavigateImages2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NavigateImages2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Image1;
    private javax.swing.JLabel Image2;
    private javax.swing.JLabel Image3;
    private javax.swing.JButton bNext;
    private javax.swing.JButton bNext2;
    private javax.swing.JButton bNext3;
    // End of variables declaration//GEN-END:variables
}
